### PR TITLE
Update index.json

### PR DESCRIPTION
**Pull request by pani-dotcom**

### CODE REVIEW

**Comment by noisymime** [comment]
Thanks for the PR! You need to include your actual tune file (msq) in the Mazda directory too

**Comment by pani-dotcom** [comment]
Hi Josh

I tried to upload the tune but then I got this message see screenshot.

Thnks
Panos

**Comment by noisymime** [comment]
I can't see the image at all either I'm afraid

**Comment by noisymime** [comment]
Closing as PR is incomplete

**Pull request closed without merging**
